### ISSUE TITLE
How to set onClickListener for Buttons in custom view

### ISSUE THREAD

**Issue by ksc91u** [ma7madfawzy/dialogPlus#1]
Say if I want to add three buttons in my custom layout.

Could you add demo how to set onclick listener for each button?

Thank you

**Comment by aligamal-dev** [comment]
Hi,
 simply you can inflate custom layout and make onClickListener on its childs, then pass this inflated view to  the dialogBuilder, for example:

`View customView = getLayoutInflater().inflate(R.layout.custom_layout, null);`

      TextView textView = customView.findViewById(R.id.textHeader);
        textView.setOnClickListener(view1 -> Toast.makeText(this, "on Click on Custom View", Toast.LENGTH_SHORT).show());
        new DialogPlusBuilder().blurBackground()
                .buildCustomLayoutDialog(customView)
                .show(this.getSupportFragmentManager(), "Custom Layout Dialog");`
you are welcome.

**Comment by aligamal-dev** [comment]
in another way you can use this method to get the layout "getCustomLayoutView()" or "getCustomLayoutBinding()"

``CustomLayoutDialog dialog = new DialogPlusBuilder() 
                  .buildCustomLayoutDialog(R.layout.activity_main);
dialog.getCustomLayoutView().findViewById(R.id.actionBtn).setOnClickListener(v->...);
       dialog.show(this.getSupportFragmentManager(), "Custom Layout Dialog");``

thanks for your feedback.
